---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:antonputra/k8s-lesson-268.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCaCfjG/u8ZAKux1VYZHeouhGTCKaUxpsYtOJHY0Q61YQAAAJi7vMzJu7zM
    yQAAAAtzc2gtZWQyNTUxOQAAACCaCfjG/u8ZAKux1VYZHeouhGTCKaUxpsYtOJHY0Q61YQ
    AAAEDY0gkx+aBSn2JIyoReTDQq4KwKQQqQ4Cw2EyurWRXNRZoJ+Mb+7xkAq7HVVhkd6i6E
    ZMIppTGmxi04kdjRDrVhAAAAFWFwdXRyYUBhbnRvbnB1dHJhLmNvbQ==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
