---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: mongodb
  labels:
    app: mongodb-exporter
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9216
  selector:
    app: mongodb-exporter
