---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: go-app
  namespace: benchmark
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
    - benchmark
  selector:
    matchLabels:
      app: go-app
  podMetricsEndpoints:
  - port: http
