---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fastapi-client
  namespace: benchmark
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
    - benchmark
  selector:
    matchLabels:
      app: fastapi-client
  podMetricsEndpoints:
  - port: metrics
