---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deno-app
  namespace: benchmark
data:
  config.yaml: |
    ---
    appPort: 8080
    db:
      user: deno_app
      password: devops123
      host: postgres.antonputra.pvt
      database: store
      maxConnections: 250
