---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-v2
  annotations:
      nginx.ingress.kubernetes.io/canary: "true"
      nginx.ingress.kubernetes.io/canary-weight: "10" # 10% of traffic
spec:
  ingressClassName: external
  rules:
    - host: catalog.example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: catalog-v2
                port:
                  number: 8080
