---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: v0.1.0
  template:
    metadata:
      labels:
        app: service-a
        istio: monitor
        version: v0.1.0
    spec:
      containers:
      - image: 424432388155.dkr.ecr.us-east-1.amazonaws.com/node-app:service-a-latest
        imagePullPolicy: Always
        name: service-a
        env:
        - name: SERVICE
          value: service-a
        - name: AWS_DEFAULT_REGION
          value: us-west-rack1
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /app/config.json
          subPath: config.yaml
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 50m
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - service-a
                - service-b
                - minio
                - mongodb
            topologyKey: "kubernetes.io/hostname"
            namespaces:
            - golang
            - nodejs
            - minio
            - mongodb
      volumes:
      - name: config
        configMap:
          name: service-a
