---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
  namespace: monitoring
spec:
  version: v2.41.0
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      component: main
  podMonitorSelector:
    matchLabels:
      component: main
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  podMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 2Gi
  replicas: 1
  logLevel: info
  logFormat: logfmt
  scrapeInterval: 5s
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 20Gi
