---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    prometheus: default
spec:
  selector:
    matchLabels:
      name: cadvisor
  endpoints:
  - port: metrics
    scrapeTimeout: 25s
